## Jupyter Notebook

### Cell
#### Command mode (회색셀)
- 셀 자체에 명령
- a(bove) : 현재 셀 위에 셀 추가
- b(elow) : 현재 셀 아래에 셀 추가
- x       : 현제 셀 자르기, 삭제 대용으로

#### Edit mode (흰색셀)
- 셀 안에 무언가를 입력
- 셀 실행 : shift + enter
- 코드
- 문서

In [ ]:
print(3 + 4)
display(3 - 4)
3 / 4
3 * 4

In [1]:
print("hello world")

hello world

In [15]:
num_list = [10, 11, 12, 13, 7, 8, 9]

for num in num_list:
    print(num)

10
11
12
13
7
8
9

### 뉴스 : 크롤링 실습

In [25]:
import requests
import bs4

url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=STC&enc=utf8&cluster=y&cluster_page=1&q=bitcoin&p=1&sort=recency'

res = requests.get(url)
news_bs = bs4.BeautifulSoup(requests.get(url).text)
ti_list = news_bs.find_all('strong', {'class': 'tit-g clamp-g'})
for ti in ti_list:
    print(ti.text)

  국힘 "현물 ETF 도입·1거래소 1은행 폐기"
  코인마켓의 덫 거래량 없는 시장, 큰손의 놀이터
  국힘 “연내 가상자산 현물ETF 거래…‘1거래소 1은행’ 폐기”
  국힘, 가상자산 7대 공약 발표...1거래소 1은행 원칙 폐기·현물 ETF 거래 승인
  국힘, 가상자산 공약…“1거래소-1은행 원칙 폐기, 연내 현물 ETF”(종합)
  [전문가 칼럼] 글로벌 금융 질서의 변화를 이끄는 비트코인
  CBDC 집중하는 한은, 스테이블코인에 눈독 들이는 은행[엠블록레터]
  무역 긴장 완화에 금값 6% 하락… 과열 우려 한풀 꺾이나
  브로토콜, 비트코인 디파이 통합 인프라 공식 출시
  다시 고개드는 비트코인 '강세론'…부자아빠 "올해 3억원 돌파한다"

In [27]:
# 덩어리 다 가져오기
div_list = news_bs.find_all('div', {'class': 'item-bundle-mid'})

for div in div_list[ :10]:
    print(div.find('a').text)
    print(div.find('a')['href'])
    print(div.find('p').text)
    print(' ')

 국힘 "현물 ETF 도입·1거래소 1은행 폐기"
http://v.daum.net/v/20250428115020522
  참가할 수 있도록 연내 제도화를 완성하겠다"고 약속했다. 아울러 "가상자산 ETF 거래의 경우 지난 1월 미국 증권거래소가 비트코인 현물 ETF 거래 승인 이후 홍콩과 영국도 현물 ETF 거래를 승인했다"며 "국내에서도 금년 내에 가상자산 현물 ETF 거래를 가능하게...

 코인마켓의 덫 거래량 없는 시장, 큰손의 놀이터
http://v.daum.net/v/20250428113628922
  단 5곳(빗썸, 업비트, 코인원, 코빗, 고팍스)뿐이다. 그 외 거래소는 원화 대신 테더(USDT)나 비트코인(BTC)으로 다른 코인을 사고판다. 이런 거래소를 ‘코인마켓 혹은 원화미지원거래소’라고 부른다. 둘째, 코인마켓의 현실은 말 그대로 사람이 거의 없는 ‘유령...

 국힘 “연내 가상자산 현물ETF 거래…‘1거래소 1은행’ 폐기”
http://v.daum.net/v/20250428112857448
  ETF 거래 승인 문제는 지난달 개최된 비공개 민당정간담회에서 논의된 사안이다. 박 의원은 “지난 1월 미국 증권거래위원회가 비트코인 현물 ETF를 승인한 이후 거래 첫날부터 뉴욕증시엔 46억달러, 약 6조5000억원에 이르는 거래량을 기록하며 대규모 신규 투자...

 국힘, 가상자산 7대 공약 발표...1거래소 1은행 원칙 폐기·현물 ETF 거래 승인
http://v.daum.net/v/20250428110851248
  수 있는 상식적 시대를 열겠다"며 "거래소 간 경쟁으로 활력에 물꼬를 트겠다"고 말했다. 지난 1월 미국 증권거래위원회에서 비트코인 현물ETF 승인한 뒤 홍콩과 영국 등에서 잇따라 현물ETF 거래를 승인한 것을 두고도 "대한민국도 지체할 시간이 없다" 며 "현물ETF...

 국힘, 가상자산 공약…“1거래소-1은행 원칙 폐기, 연내 현물 ETF”(종합)
http://v.daum.net/v/20250428110638115
  참여할 수 있도록 연내에 제도화를 완성한다는 계획이다. 올해 중 가상자산 현물ETF 거래도 허용한다. 가상자산 현물ETF란 비트코인이나 이더리움 같은 가상자산(암호화폐)을 실제로 사서 보유하고 가격 움직임을 따라가는 상장지수펀드다. 박 의원은 “1월 미국...

 [전문가 칼럼] 글로벌 금융 질서의 변화를 이끄는 비트코인
http://v.daum.net/v/20250428105519396
  비트코인은 은행이나 정부 같은 중앙 기관의 개입 없이 개인 간에 안전하게 가치를 전송할 수 있도록 설계됐다. 발행량은 2100만개로 제한돼 있으며, 이는 기존 법정화폐처럼 무한정 발행될 수 없다는 점에서 통화 인플레이션에 대한 방어 수단이 된다. 2009년 출시...

 CBDC 집중하는 한은, 스테이블코인에 눈독 들이는 은행[엠블록레터]
http://v.daum.net/v/20250428105407326
  일부 업체는 실명계좌 확보 위해 은행 접촉 중 업계는 원화 거래 재개 기대하며 버티고 있으나, 경영 지속은 불투명 손정의, 비트코인에 ‘통큰’ 베팅…美 상무장관 아들도 합세 소프트뱅크가 테더, 비트파이넥스 등과 함께 비트코인 투자 벤처 ‘21캐피털’ 설립...

 무역 긴장 완화에 금값 6% 하락… 과열 우려 한풀 꺾이나
http://v.daum.net/v/20250428104711896
  다만 금에 대한 근본적 수요는 여전히 견고하다는 시각도 있다. 블룸버그 산하 연구기관인 블룸버그 인텔리전스는 금과 비트코인이 최근 비슷한 급등락 패턴을 보였지만 내재 변동성은 안정적 흐름을 유지하고 있다고 진단했다. 또 금값 조정이 불가피하더라도 장기...

 브로토콜, 비트코인 디파이 통합 인프라 공식 출시
http://v.daum.net/v/20250428104219662
  (지디넷코리아=김한준 기자)비트코인 브릿지 엑스링크가 브로토콜(Brotocol)로 리브랜딩하며 ‘비트코인 기반 통합 디파이 인프라 플랫폼’을 공식 출시했다고 28일 밝혔다. 브로토콜은 래핑 없이 비트코인 네트워크 안에서 디파이 기능과 외부 유동성을 바로 활용할...

 다시 고개드는 비트코인 '강세론'…부자아빠 "올해 3억원 돌파한다"
http://v.daum.net/v/20250428104200637
  [한국경제TV 홍성진 외신캐스터] 비트코인이 연초 낙폭을 회복하고 꾸준히 상승 중인 가운데 강세장이 돌아왔다는 평가들이 나오고 있다. 27일(현지시간) 야후 파이낸스에 따르면 세계적인 베스트셀러 '부자 아빠 가난한 아빠'의 저자 로버트 기요사키는 비트코인이...

In [31]:
# 덩어리 다 가져오기
div_list = news_bs.find_all('div', {'class': 'item-bundle-mid'})

new_list = []
for div in div_list[ :10]:
    temp = {}
    temp['title'] = div.find('a').text
    temp['link'] = div.find('a')['href']
    temp['summary'] = div.find('p').text
    new_list.append(temp)

In [37]:
import pandas as pd

pd.DataFrame(new_list)

,title,link,summary
0,"국힘 ""현물 ETF 도입·1거래소 1은행 폐기""",http://v.daum.net/v/20250428115020522,"참가할 수 있도록 연내 제도화를 완성하겠다""고 약속했다. 아울러 ""가상자산 ET..."
1,"코인마켓의 덫 거래량 없는 시장, 큰손의 놀이터",http://v.daum.net/v/20250428113628922,"단 5곳(빗썸, 업비트, 코인원, 코빗, 고팍스)뿐이다. 그 외 거래소는 원화 ..."
2,국힘 “연내 가상자산 현물ETF 거래…‘1거래소 1은행’ 폐기”,http://v.daum.net/v/20250428112857448,ETF 거래 승인 문제는 지난달 개최된 비공개 민당정간담회에서 논의된 사안이다....
3,"국힘, 가상자산 7대 공약 발표...1거래소 1은행 원칙 폐기·현물 ETF 거래 승인",http://v.daum.net/v/20250428110851248,"수 있는 상식적 시대를 열겠다""며 ""거래소 간 경쟁으로 활력에 물꼬를 트겠다""고..."
4,"국힘, 가상자산 공약…“1거래소-1은행 원칙 폐기, 연내 현물 ETF”(종합)",http://v.daum.net/v/20250428110638115,참여할 수 있도록 연내에 제도화를 완성한다는 계획이다. 올해 중 가상자산 현물E...
5,[전문가 칼럼] 글로벌 금융 질서의 변화를 이끄는 비트코인,http://v.daum.net/v/20250428105519396,비트코인은 은행이나 정부 같은 중앙 기관의 개입 없이 개인 간에 안전하게 가치를...
6,"CBDC 집중하는 한은, 스테이블코인에 눈독 들이는 은행[엠블록레터]",http://v.daum.net/v/20250428105407326,일부 업체는 실명계좌 확보 위해 은행 접촉 중 업계는 원화 거래 재개 기대하며 ...
7,무역 긴장 완화에 금값 6% 하락… 과열 우려 한풀 꺾이나,http://v.daum.net/v/20250428104711896,다만 금에 대한 근본적 수요는 여전히 견고하다는 시각도 있다. 블룸버그 산하 연...
8,"브로토콜, 비트코인 디파이 통합 인프라 공식 출시",http://v.daum.net/v/20250428104219662,(지디넷코리아=김한준 기자)비트코인 브릿지 엑스링크가 브로토콜(Brotocol)...
9,"다시 고개드는 비트코인 '강세론'…부자아빠 ""올해 3억원 돌파한다""",http://v.daum.net/v/20250428104200637,[한국경제TV 홍성진 외신캐스터] 비트코인이 연초 낙폭을 회복하고 꾸준히 상승 ...

In [47]:
# URL 셋팅
def get_newsData(search, page):
    url = 'https://search.daum.net/search?w=news&nil_search=btn&DA=STC&enc=utf8&cluster=y&cluster_page=1&q={}&p={}&sort=recency'
    real_url = url.format('search', 3)

    resp = requests.get(real_url)
    news_bs = bs4.BeautifulSoup(resp.text)

    div_list = news_bs.find_all('div', {'class': 'item-bundle-mid'})[:10]
    news_list = []
    for div in div_list:
        temp = {}
        temp['title'] = div.find('a').text
        temp['link'] = div.find('a')['href']
        temp['summary'] = div.find('p').text
        news_list.append(temp)

    return news_list

In [57]:
news_result = []
for p in range(1,11):
    news_result += get_newsData('경제', p)

In [58]:
len(news_result)

100

In [61]:
result = pd.DataFrame(news_result)
display(result)

,title,link,summary
0,"Seoul, Beijing at odds over West Sea structur...",http://v.daum.net/v/20250424153228481,"second subcommittee, on Practical Cooperatio..."
1,[스타트업-ing] 크립토랩 “해킹 무의미한 동형암호 기술의 글로벌 리더로”,http://v.daum.net/v/20250424100609091,전체가 복호화되어 해커에게 노출되는 문제가 있었다. 하지만 크립토랩 동형암호 기...
2,"Man's best friends play vital, courageous rol...",http://v.daum.net/v/20250424090037013,Fire Lieutenant Jang Taek-yong of the Gyeong...
3,[시승기] 기아 첫 전기 세단 등장…'EV4' 직접 타보니,http://v.daum.net/v/20250424083012119,무게중심을 낮춰 전체적인 안정감을 더한다. 기아 EV4의 센터페시아. 햅틱 방식...
4,Gilgo Beach-Serial Killings,http://v.daum.net/v/20250423235726507,FILE - Crime scene investigators use metal d...
...,...,...,...
95,INDIA KASHMIR TERROR ATTACK,http://v.daum.net/v/20250423185016750,epa12048538 An Indian Air Force helicopter c...
96,Samsung at center of Google's crucial antitru...,http://v.daum.net/v/20250423180020048,"trial, which kicked off on Monday. The alleg..."
97,U.S. antitrust trial targets Google’s AI deal...,http://v.daum.net/v/20250423174459391,of Justice (DOJ) said that “Google can use a...
98,Cluely raises $5.3 million in seed funding fo...,http://v.daum.net/v/20250423144429184,Cluely founder Roy Lee demonstrates using th...
99,Police begin search of Giheung Station in Gye...,http://v.daum.net/v/20250423134537624,about the post that morning and requested co...

### 스타벅스 매장 : 비동기 웹 크롤링 실습

In [ ]:
# URL 셋팅

In [131]:
url = "https://www.starbucks.co.kr/store/getStore.do?r=AAAPQ04Y9N"
data = {
  "in_biz_cds": 0,
  "in_scodes": 0,
  "ins_lat": 37.56682,
  "ins_lng": 126.97865,
  "search_text": "",
  "p_sido_cd": "01",
  "p_gugun_cd": "",
  "isError": True,
  "in_distance": 0,
  "in_biz_cd": "",
  "iend": 1000,
  "searchType": "C",
  "set_date": "",
  "rndCod": "D32NU54YUP",
  "all_store": 0,
  "T03": 0,
  "T01": 0,
  "T27": 0,
  "T12": 0,
  "T09": 0,
  "T30": 0,
  "T05": 0,
  "T22": 0,
  "T21": 0,
  "T36": 0,
  "T43": 0,
  "Z9999": 0,
  "T64": 0,
  "T66": 0,
  "P02": 0,
  "P10": 0,
  "P50": 0,
  "P20": 0,
  "P60": 0,
  "P30": 0,
  "P70": 0,
  "P40": 0,
  "P80": 0,
  "whcroad_yn": 0,
  "P90": 0,
  "P01": 0,
  "new_bool": 0
}

resp = requests.post(url, data)
len(resp.json()['list'])

639

In [135]:
resp_df = pd.DataFrame(resp.json()['list'])
display(resp_df)

,seq,sido_cd,sido_nm,gugun_cd,gugun_nm,code_order,view_yn,store_num,sido,gugun,...,t30,t36,t27,t29,t43,t48,z9999,t64,t66,p02
0,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
1,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
2,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
3,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
4,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
635,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
636,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
637,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
638,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0

In [137]:
# 전체 데이터가 모두 None이거나 0인 칼럼 삭제

resp_df_cleaned = resp_df.dropna(axis=1, how='all')
resp_df_cleaned = resp_df_cleaned.loc[:, ~(resp_df_cleaned == 0).all()]
resp_df_cleaned = resp_df_cleaned.loc[:, ~(resp_df_cleaned == '').all()]

# 결과 출력
resp_df_cleaned

,s_code,s_name,tel,fax,sido_code,sido_name,gugun_code,gugun_name,addr,new_state,...,defaultimage,istart,iend,open_dt,doro_address,my_siren_order_store_yn,whcroad_yn,store_area_code,lat,lot
0,1509,역삼아레나빌딩,1522-3232,02-568-3763,01,서울,0101,강남구,서울특별시 강남구 역삼동 721-13 아레나빌딩,None,...,/upload/store/2019/06/[3762]_20190612101444_j4...,1,60,20190613,서울특별시 강남구 언주로 425 (역삼동),N,WHCROAD,A01,37.501087,127.043069
1,1434,논현역사거리,1522-3232,02-3442-3673,01,서울,0101,강남구,서울특별시 강남구 논현동 142-2 정일빌딩,None,...,/upload/store/2018/12/[3672]_20181211120009_t9...,1,60,20181123,서울특별시 강남구 강남대로 538 (논현동),N,,A01,37.510178,127.022223
2,1595,신사역성일빌딩,1522-3232,02-547-3859,01,서울,0101,강남구,서울특별시 강남구 논현동 18-4 성일빌딩,None,...,/upload/store/2022/01/[3858]_20220127064243_5k...,1,60,20191219,서울특별시 강남구 강남대로 584 (논현동),N,,A01,37.5139309,127.0206057
3,1527,국기원사거리,1522-3232,02-568-3669,01,서울,0101,강남구,서울특별시 강남구 역삼동 648-22 동찬빌딩,None,...,/upload/store/2019/07/[3669]_20190730073527_5n...,1,60,20190731,서울특별시 강남구 테헤란로 125 (역삼동),N,WHCROAD,A01,37.499517,127.031495
4,1468,대치재경빌딩,1522-3232,02-568-3705,01,서울,0101,강남구,서울특별시 강남구 대치동 599 대원빌딩,None,...,/upload/store/2023/12/[3703]_20231217121347_eq...,1,60,20190214,서울특별시 강남구 남부순환로 2947 (대치동),N,WHCROAD,A01,37.494668,127.062583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,493,상봉역,1522-3232,02-433-8486,01,서울,0125,중랑구,"서울특별시 중랑구 상봉동 100-2,3,4번지",Y,...,/upload/store/2019/10/[9686]_20191001110003_28...,1,60,20120323,서울특별시 중랑구 망우로 307 (상봉동),N,WHCROAD,A01,37.59689,127.08647
635,1668,묵동,1522-3232,02-971-3937,01,서울,0125,중랑구,서울특별시 중랑구 묵동 169-12 로프트원 태릉입구역 1층,None,...,/upload/store/2020/06/[3936]_20200628090702_8k...,1,60,20200630,"서울특별시 중랑구 동일로 952 (묵동, 로프트원 태릉입구역) 1층",N,WHCROAD,A01,37.615368,127.076633
636,2345,망우동,1522-3232,--,01,서울,0125,중랑구,서울특별시 중랑구 망우동 488-5,None,...,/upload/store/2025/01/[4611]_20250102030458_sy...,1,60,20241128,서울특별시 중랑구 망우로 407 (망우동),N,WHCROAD,A01,37.5995083771241,127.097538751682
637,2002,양원역,1522-3232,02-433-4308,01,서울,0125,중랑구,"서울특별시 중랑구 망우동 618 B1~1층일부 B101,B102,101,102 4개호실",None,...,/upload/store/2022/08/[4307]_20220824060637_yg...,1,60,20220825,서울특별시 중랑구 양원역로10길 3 (망우동),N,WHCROAD,A01,37.6066536267232,127.106359790053
638,1749,중화역,1522-3232,02-435-3802,01,서울,0125,중랑구,"서울특별시 중랑구 중화동 306-68 중화동 HS빌딩 1,2층",None,...,/upload/store/2023/01/[3801]_20230116114149_zi...,1,60,20201222,서울특별시 중랑구 봉화산로 35 1층,N,WHCROAD,A01,37.60170912407773,127.07841136432036

### 공공 데이터 포털 : API 실습

In [109]:
KEY = 'MbiNtPqkbuQGusxSSkIcU2qBdqqFivuOtaUsKPTn1fNFLbcOhNunrI74%2BfgD9RXkBxaJwUimRp%2BOcSrLa7vy%2FA%3D%3D'
request_url = "http://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade?LAWD_CD={}&DEAL_YMD={}&serviceKey={}"
real_url = request_url.format(11110, 202412, KEY)

In [111]:
real_url

'http://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade?LAWD_CD=11110&DEAL_YMD=202412&serviceKey=MbiNtPqkbuQGusxSSkIcU2qBdqqFivuOtaUsKPTn1fNFLbcOhNunrI74%2BfgD9RXkBxaJwUimRp%2BOcSrLa7vy%2FA%3D%3D'

In [113]:
res = requests.get(real_url, verify=False)
res.text

'<?xml version="1.0" encoding="utf-8" standalone="yes"?><response><header><resultCode>000</resultCode><resultMsg>OK</resultMsg></header><body><items><item><aptDong>116</aptDong><aptNm>인왕산아이파크</aptNm><buildYear>2008</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>103,000</dealAmount><dealDay>28</dealDay><dealMonth>12</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>59.993</excluUseAr><floor>12</floor><jibun>60</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.03.05</rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>무악동</umdNm></item><item><aptDong> </aptDong><aptNm>동대문</aptNm><buildYear>1966</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>40,000</dealAmount><dealDay>17</dealDay><dealMonth>12</dealMonth><dealYear>2024</dealYear><dealingGbn>직거래</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>28.8</excluUseAr><floor>5</floor><jibun>328-17</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.01.15</rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>창신동</umdNm></item><item><aptDong>101</aptDong><aptNm>종로센트레빌</aptNm><buildYear>2008</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>85,500</dealAmount><dealDay>20</dealDay><dealMonth>12</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>59.92</excluUseAr><floor>3</floor><jibun>2-1</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.03.20</rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>숭인동</umdNm></item><item><aptDong>209</aptDong><aptNm>경희궁자이(2단지)</aptNm><buildYear>2017</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>233,000</dealAmount><dealDay>31</dealDay><dealMonth>12</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>84.614</excluUseAr><floor>4</floor><jibun>199</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.03.27</rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>홍파동</umdNm></item><item><aptDong>제101</aptDong><aptNm>아남1</aptNm><buildYear>1995</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>120,000</dealAmount><dealDay>7</dealDay><dealMonth>12</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>84.9</excluUseAr><floor>12</floor><jibun>4</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.02.20</rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>명륜2가</umdNm></item><item><aptDong>206</aptDong><aptNm>창신쌍용2</aptNm><buildYear>1993</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>87,000</dealAmount><dealDay>25</dealDay><dealMonth>12</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>115.53</excluUseAr><floor>14</floor><jibun>703</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.03.07</rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>창신동</umdNm></item><item><aptDong> </aptDong><aptNm>효자</aptNm><buildYear>1999</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>22,000</dealAmount><dealDay>23</dealDay><dealMonth>12</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>61.49</excluUseAr><floor>5</floor><jibun>5-1</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.12.24</rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>통인동</umdNm></item><item><aptDong>제101</aptDong><aptNm>아남1</aptNm><buildYear>1995</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>125,000</dealAmount><dealDay>9</dealDay><dealMonth>12</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>84.9</excluUseAr><floor>3</floor><jibun>4</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.02.26</rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>명륜2가</umdNm></item><item><aptDong>106</aptDong><aptNm>인왕산아이파크</aptNm><buildYear>2008</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>144,000</dealAmount><dealDay>3</dealDay><dealMonth>12</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>114.931</excluUseAr><floor>4</floor><jibun>60</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.12.20</rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>무악동</umdNm></item><item><aptDong>103</aptDong><aptNm>롯데낙천대</aptNm><buildYear>2001</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>113,000</dealAmount><dealDay>17</dealDay><dealMonth>12</dealMonth><dealYear>2024</dealYear><dealingGbn>직거래</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>133.34</excluUseAr><floor>11</floor><jibun>72</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.12.19</rgstDate><sggCd>11110</sggCd><slerGbn>법인</slerGbn><umdNm>평창동</umdNm></item></items><numOfRows>10</numOfRows><pageNo>1</pageNo><totalCount>13</totalCount></body></response>'